### ISSUE TITLE
Level Editor Menu Display Error Message on macOS

### ISSUE THREAD

**Issue by CreativeMasterBonin** [1j01/janitorial-android#2]
Hey, just wanted to let you know that your remake works nearly perfectly (and it's identical to the Shockwave Version!).

One problem is that I cannot press any of the level editor menu buttons (the bottom row) without an error message appearing. Not sure if this is a macOS thing only or happens on all platforms.

Browser Used: Firefox 106-64bit
OS: macOS Monterey
Game Version: Latest Public Web Page

Hope there is a way to fix this little issue, otherwise, everything else seemed to work fine.

**Comment by 1j01** [comment]
Ah, I see, it's not working on Firefox because the [`ariaKeyShortcuts`](https://developer.mozilla.org/en-US/docs/Web/API/Element/ariaKeyShortcuts) property is unsupported, and I'm relying on that to generate simulated keyboard events to trigger the different functions. I can use `getAttribute` instead as an easy fix.

Thanks for reporting!
